### ISSUE TITLE
Feature Request: Add Chinese language to i18n list

### ISSUE THREAD

**Issue by wparad** [Authress-Engineering/openapi-explorer#189]
Hey @photino, I saw your request over in RapiDoc. We operate a long time fork over here that already supports i18n. So if you would be interested in creating the translation file, it should already work out of the box.

You can find the existing translation keys in here: https://github.com/Rhosys/openapi-explorer/tree/release/2.0/src/languages

**Comment by photino** [comment]
Thanks！I may create a `zh.js` translation file.
