### ISSUE TITLE
Feature Request:  show `operationId` in the view for a single endpoint (operation)

### ISSUE THREAD

**Issue by modellurgist** [Authress-Engineering/openapi-explorer#195]
That `operationId` has special meaning in the case of the specification generated by my web framework, and it helps quickly locate the code responsible for serving requests for that operation.

**Comment by wparad** [comment]
Hmm, that's an interesting idea. There should be a `<slot>` for each of the operations that would allow you to automatically extend the content in the operation view. Is that sufficient or would you say you need something more?

**Comment by wparad** [comment]
Closing as this is solved by using the slot.
