### ISSUE TITLE
No clickable or copyable anchors for schemas page

### ISSUE THREAD

**Issue by addshore** [Authress-Engineering/openapi-explorer#203]
For example, on https://authress.io/app/#/api?route=cmp--schemas there are many schemas.
It would be nice to be able to link directly to a heading on this page, such as "RoleCollection" more easily.

I see that the headings already had IDs such as `cmp--schemas-connectioncollection` and these work when manually crafting URLs.
However as the individual schemas are not clickable in the side bar, crafting this URL is harder than for the routes.

I'd propose something like...

A link icon on hover that appears somewhere, so you can right click and copy link

![image](https://github.com/Authress-Engineering/openapi-explorer/assets/3308769/0ea7bf8b-9520-4a61-bbdc-ed616ce14912)
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/3308769/7866d22e-0993-441f-b721-ca4f8906ce14)

Or a larger change would be to list schemas in the side bar to be clickable.

**Comment by wparad** [comment]
That's a great idea, I'm not totally sure how much work it would take to make the navbar happen, but for sure both of these things make sense to be included. We would be definitely open to multiple PRs one for each of these, to tackle the UX improvement.

**Comment by wparad** [comment]
This is now added.

**Comment by addshore** [comment]
Amazing, I look forward to the next release on npm! :)

**Comment by wparad** [comment]
Releases happen automatically, which means this was released 4 days ago.

**Comment by addshore** [comment]
It looks like the automation might be broken due to the repo move
https://github.com/Authress-Engineering/openapi-explorer/actions/runs/6922661368/workflow#L42 :)

**Comment by wparad** [comment]
@addshore this should be published now, thanks for the hint.

**Comment by addshore** [comment]
Pulled the update and I certainly have clickable links, oddly the anchor links don't seem to work for me now on my own deployment, I see them still working on https://authress.io/app/#/api?route=cmp--schemas-extension for example, but I don't see the clickable link there.

An example would be https://docs-next.lightbug.io/apis/v1#?route=cmp--schemas-deviceconfig
I'm just writing a note here so I remember, and I'll try to investigate what is happening a little more.

**Comment by wparad** [comment]
I didn't look what the scrollTo function is doing here, but I thought it operated the same, I believe both the click and the scheme link in the component panel are calling the same thing.

Our tester seems to have the same functionality both ways, so I'm not sure what I'm missing here: https://authress.io/app/#/api?route=cmp--schemas-tags
