### ISSUE TITLE
Force localisation to english

### ISSUE THREAD

**Issue by gdec31** [Authress-Engineering/openapi-explorer#207]
Hello,

I have my open api explorer that works well, thank for all contributor.

My API documentation is only in english and, if I configured my browser to support the french localisation (i'm french), I have my openapi explorer  mixed between french and english. I just want to have the english locale.

Is it possible to have an option to force the usage of a localisation ?

**Comment by wparad** [comment]
Hmmm, that's a good point. While we wouldn't want to have a setting to do this, it does make sense to try to source the language of the spec from the spec itself. Does openopi spec contain a property that specifies the language/locale of the spec?

**Comment by gdec31** [comment]
There seems to be no solution yet in the openapi spec :
https://github.com/OAI/OpenAPI-Specification/issues/274

A possible solution could be to use the overlay  https://github.com/OAI/OpenAPI-Specification/issues/1722

**Comment by wparad** [comment]
I don't think an overlay is necessarily the best approach here, it would be a trade-off with just adding a custom vendor field.

Actually looking at https://github.com/OAI/OpenAPI-Specification/issues/70, I saw the suggestion of potentially using the `Accept-Language` and `Content-Language` headers. Some more thought might need to go into that, but that starts to feel like the potentially right direction.

The Argument being, the navigator tells your spec which languages to select, and then your spec language header controls the actual display on our side.

I totally agree having part of the spec in one language and the rest of the spec in another doesn't make sense. So I do want to say this issue will be dealt with as soon as it seems like there is a good path forward here.

**Comment by wparad** [comment]
This is now supported via the `info.x-locale` property in the latest version of the library.
