### ISSUE TITLE
BasicAuth Label missing

### ISSUE THREAD

**Issue by splitbrain** [Authress-Engineering/openapi-explorer#213]
My API supports JWT token auth and basic auth, which has been configured like this in the spec:

```
    "security": [
        {
            "basicAuth": []
        },
        {
            "jwt": []
        }
    ],
```

This generally works fine in the explorer, but it seems there is some kind of label missing for the basicAuth scheme?

![screenshot-localhost-2024 01 05-12_26_27](https://github.com/Authress-Engineering/openapi-explorer/assets/86426/8ef473ca-88d1-470c-a34e-0de3c4d69ae1)
![screenshot-localhost-2024 01 05-12_27_58](https://github.com/Authress-Engineering/openapi-explorer/assets/86426/8751d38f-811b-4708-bb84-dccd9dc07b16)

Not a huge deal, just looks a bit weird.

**Comment by wparad** [comment]
Thanks for reporting this. It has now been fixed in the latest version of the library: `2.1.650`
