### ISSUE TITLE
Hide the sidebar & show the full spec

### ISSUE THREAD

**Issue by michael-wolfenden** [Authress-Engineering/openapi-explorer#217]
We are attempting to migrate from rapiddoc which had a `render-style`  property which toggled whether the sidebar was hidden or not. 

Does `openapi-explorer` have a property that allows hiding the sidebar?

**Comment by wparad** [comment]
It isn't clear to me what the feature request here is. The OpenAPI Explorer is responsible, so on mobile devices the view automatically renders a display that works better on mobile. That view actually does not show the sidebar.

So if I understand the request, this already works correctly. But if it is about something else, feel free to add additional context here, and I'll reopen the ticket.

**Comment by michael-wolfenden** [comment]
The feature request is for a toggle to always show the openapi-explorer in mobile mode (ie without the sidebar) regardless of the the current screen breakpoint.

Rapidoc calls this view mode. They have an example here: https://rapidocweb.com/examples/example1.html

I hope that clarifies things

**Comment by wparad** [comment]
Hmm, I see. Could you explain more about how would account for the UX degradation for a user now no longer being able to jump to the section they care about? Surely this will be worse for them right? How do you plan to counteract that new problem?

**Comment by michael-wolfenden** [comment]
> Could you explain more about how would account for the UX degradation for a user now no longer being able to jump to the section they care about?

Do you mean by not seeing the sidebar? I'm must be misunderstanding but if you consider this UX degragation then doesn't your existing mobile mode suffer this problem?

**Comment by wparad** [comment]
Yes and no. The mobile view is optimized for **small**, **touch**, and **optimized** device devices that are small have touch capabilities and limited interactability. Just like using the mobile version of your mobile apps in a desktop browser wouldn't make sense, this display doesn't make sense here either.

Likewise when changes are made to the "mobile" version it will likely break things for an expanded view. That is, the expectation during development of this view is that it is for mobile only.

> Our users preferred the.view only mode as the scrolling behavior of the nar bar as well as the the scrolling of the operation documentation confused them.

Great, let's talk about this. This feedback would definitely help us refine what we display and what is available. Can you say more about what is confusing here? We can then take that and figure out what the optimized result could be. It might be a  whole new display or specific quality of life improvements.

**Comment by wparad** [comment]
Closing due to lack of feedback. If more information surfaces related to the problems with the navbar, please feel free to add additional context to this issue. Thanks you.
