### ISSUE TITLE
Feature Request: Additional empty slots

### ISSUE THREAD

**Issue by michael-wolfenden** [Authress-Engineering/openapi-explorer#218]
It would be nice to have additional empty slots between each of the main slots like `overview` and `overview-api-description` allowing you to add additional content between each slot. 

In our scenario we want to add a `Download OpenApi Specification` button between the `overview` and `overview-api-description` slot, however this doesn't appear to be possible without overwriting the entire contents of the `overview` which we are hoping to avoid.

My suggestion would be empty `before` and `after` slots for each existing slot (where it makes sense). So `before-overview`, `after-overview`, `before-overview-api-description`, `after-overview-api-description`  etc

**Comment by wparad** [comment]
In `2.1.656` there are three new slots: https://github.com/Authress-Engineering/openapi-explorer/blob/release/2.1/docs/documentation.md#slots
