### ISSUE TITLE
Get the schema name into the model tab

### ISSUE THREAD

**Issue by gdec31** [Authress-Engineering/openapi-explorer#220]
Hello,

I use the [openapi generator](https://openapi-generator.tech/),  and it would be ideal if the openapi documentation could specify the name of the schema to be used, in order to know the output schema of an endpoint.

Is it possible to add the schema name into the model tab ?

**Comment by wparad** [comment]
Would you be able to add a spec and a quick mock up of the expected visual change?

**Comment by gdec31** [comment]
Yes, something like that (DtoArtefact is the schema name.
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/26168420/0c4ee5fa-2b96-4a59-88c2-373d22cdc2d2)

**Comment by wparad** [comment]
@gdec31 can you also include the spec? Thanks!

**Comment by wparad** [comment]
This is now available in `2.1.658`, by default it will use the `schema ref name` but you can specify the title.
