### ISSUE TITLE
Missing response output

### ISSUE THREAD

**Issue by splitbrain** [Authress-Engineering/openapi-explorer#224]
I have an autogenerated API spec available at https://www.dokuwiki.org/lib/exe/openapi.php?spec=1 Using the API Explorer works fine in general, except one endpoint does not display the Response part: http://localhost/devel/dokuwiki/lib/exe/openapi.php?do=spec#?route=post-/core.whoAmI

When switching between different endpoints and then switching to the whoAmI endpoint the Response part of the last shown endpoint is shown.

API spec and this specific endpoint are shown correctly in the Swagger next editor. I have no idea what's wrong. I didn't notice this problem in any other of the auto generated endpoints.

![screenshot-localhost-2024 02 06-12_49_18](https://github.com/Authress-Engineering/openapi-explorer/assets/86426/1885df8b-86e0-4339-805e-b6a15cbb67ec)

The definition of the endpoint looks like this:

    "/core.whoAmI": {
            "post": {
                "operationId": "core.whoAmI",
                "summary": "Info about the currently authenticated user",
                "description": "",
                "tags": [
                    "User"
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "null"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Result",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "description": "",
                                            "examples": [
                                                {}
                                            ],
                                            "type": "object",
                                            "properties": {
                                                "login": {
                                                    "description": "The login name of the user",
                                                    "type": "string"
                                                },
                                                "name": {
                                                    "description": "The full name of the user",
                                                    "type": "string"
                                                },
                                                "mail": {
                                                    "description": "The email address of the user",
                                                    "type": "string"
                                                },
                                                "groups": {
                                                    "description": "The groups the user is in",
                                                    "type": "array"
                                                },
                                                "isadmin": {
                                                    "description": "Whether the user is a super user",
                                                    "type": "boolean"
                                                },
                                                "ismanager": {
                                                    "description": "Whether the user is a manager",
                                                    "type": "boolean"
                                                }
                                            }
                                        },
                                        "error": {
                                            "type": "object",
                                            "description": "Error object in case of an error",
                                            "properties": {
                                                "code": {
                                                    "type": "integer",
                                                    "description": "The error code",
                                                    "examples": [
                                                        0
                                                    ]
                                                },
                                                "message": {
                                                    "type": "string",
                                                    "description": "The error message",
                                                    "examples": [
                                                        "Success"
                                                    ]
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

**Comment by wparad** [comment]
It's just failing to render because the `groups` property is an array with no `items` definition, which was considered broken by the explorer. I've added a fallback for this so now it will render correctly.

![image](https://github.com/Authress-Engineering/openapi-explorer/assets/5056218/b12289f8-84ae-4189-9963-1c65dea245d2)

This is fixed in `2.1.665`
