### ISSUE TITLE
Field column width is too small, needs to be adjustable

### ISSUE THREAD

**Issue by neongrau** [Authress-Engineering/openapi-explorer#228]
In the Model Schema (table view), when you have nested attributes (e.g. JSONAPI standard data/attributes/field_name) the field names can become too long to be displayed properly.

Would be better if the field width were adjustable (CSS).

See the last field here:
![Bildschirmfoto 2024-02-07 um 10 33 47](https://github.com/Authress-Engineering/openapi-explorer/assets/179209/a86d81f6-5b91-467f-a520-d4f4fd6c1079)

**Comment by wparad** [comment]
Schema columns will now automatically resize, but if there is something about that you would still like to override, you can also use the new **css parts** - `schema-key` (or `schema-table-header`, `schema-type`, `schema-description`) to override. This can be found in latest available version.

**Comment by neongrau** [comment]
Again, thank you very much. I set a larger width on part(schema-key) that fixed it.
I didn't see any auto resizing though.
