### ISSUE TITLE
dropdown lists duplicates of possible request headers for content-type

### ISSUE THREAD

**Issue by neongrau** [Authress-Engineering/openapi-explorer#236]
one for each response (all of same type)

![Bildschirmfoto 2024-02-13 um 10 57 05](https://github.com/Authress-Engineering/openapi-explorer/assets/179209/86f6dbb2-4d7b-425d-b2cb-89f316828e4b)

**Comment by wparad** [comment]
Cool, that should be an easy fix, want to look into making a PR for that?
