### ISSUE TITLE
Display of a public API 

### ISSUE THREAD

**Issue by gdec31** [Authress-Engineering/openapi-explorer#241]
Hello,

I have a public API which is not subject to any authorization type. 

**Step to reproduce **

-  Select a public endpoint (You can found an extract of the schema below)

**Actual behavior **

- On the top right of endpoint page I have this :
![image](https://github.com/Authress-Engineering/openapi-explorer/assets/26168420/334bd7b3-9c6c-456d-b6cd-7062453becce)

**Expected behavior **

- Should display nothing

_An extract of the schema :_ (there is no security part) 
```javascript
  "/saml" : {
      "get" : {
        "tags" : [ "Server" ],
        "summary" : "Get the SP metadata",
        "description" : "Get the service provider metadata.",
        "operationId" : "getSpMetadata",
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
          },
          "204" : {
            "description" : "No content."
          }, "500" : {
            "description" : "Internal server error."
          }
        }
      }
    },```

**Comment by wparad** [comment]
I'm struggling to reproduce this, we'll need a full minimal reproduction spec in order to validate this. Can you share that?

**Comment by gdec31** [comment]
Below a simple schema to reproduce the case.
I reproduce on https://authress-engineering.github.io/openapi-explorer/ 

```javascript
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "The REST API",
    "description" : "Descr.",
    "version" : "2",
    "x-locale" : "en_US"
  },
  "servers" : [ {
    "url" : "/api/"
  } ],
  "security" : [ {
    "bearerAuth" : [ ]
  }, {
    "basicAuth" : [ ]
  } ],
  "tags" : [ {
    "name" : "Server",
    "description" : "The server API"
  }],
  "paths" : {
    "/saml" : {
      "get" : {
        "tags" : [ "Server" ],
        "summary" : "Get the SP metadata",
        "description" : "Get the service provider metadata",
        "operationId" : "getSpMetadata",
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/xml" : { }
            }
          },
          "204" : {
            "description" : "No content."
          },
          "500" : {
            "description" : "Internal server error."
          }
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "bearer" : {
        "type" : "http",
        "scheme" : "bearer"
      },
      "basic" : {
        "type" : "http",
        "scheme" : "basic"
      }
    }
  }
}
```

**Comment by gdec31** [comment]
I simplify the schema and remove the others endpoints (100+).

But I have : 
- one endpoint that use basic authentication
- one public endpoint (the previous example)
- the others use bearer authentication

But seems ok to just add _"security" : [  ]_ like you describe.

Thanks !

**Comment by wparad** [comment]
I'm not following what the issue is honestly. In the first endpoint, set it to basic, in the second endpoint, set it an empty array, and at the top level set it to be an array with just the bearer type. That is the guidance from the Open API Initiative specification for how to implement your scenario.

**Comment by wparad** [comment]
no problem at all. Cheers.
