### ISSUE TITLE
„Full Request“ line not always updated

### ISSUE THREAD

**Issue by Xarno** [Authress-Engineering/openapi-explorer#264]
We found, that the curl example on the Full Request line is not always updated when initially loading and when switching between different requests. It looks like there need to be a required parameter to trigger this bug.

This is visible on your example page too.
1. https://authress-engineering.github.io/openapi-explorer/#?route=put-/v1/clients/-clientId- 
2. take note of the curl
3. click on the Delete service client
4. curl line is not changed
5. curl line does update if you change all the required parameters (see Delete service client access key)

**Comment by wparad** [comment]
This is fixed now in the latest version. Thanks for reporting this.
